apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: serviceconfigs.config.istio.io
spec:
  group: config.istio.io
  names:
    kind: ServiceConfig
    listKind: ServiceConfigList
    plural: serviceconfigs
    singular: serviceconfig
  scope: Namespaced
  version: v1alpha2

